### ISSUE TITLE
Extension crashed

### ISSUE THREAD

**Issue by rflgrt** [cyprienruffino/ulauncher-tex-to-unicode#3]
On Ubuntu 23.04 with ULauncher v15.5.6 the extension appears as crashed in ULaunchers Extension Overview and the "tex" command does not work.

pylatexenc was installed using pipx, latexencode and latex2text are availabe in the terminal.

**Comment by cyprienruffino** [comment]
Hello ! Thanks for raising this issue :)

Do you have any logs ?
You can find these by running ULauncher in a terminal, or in
.local/share/ulauncher/last.log

**Comment by rflgrt** [comment]
Hi, 

I already found the problem. I installed pylatexenc using pipx since in Ubuntu system wide installation using pip is no longer supported. This installs programs in a virtual environment and makes them available system wide, so I could call latexencode in the terminal, but I realized I could not import it into python3.

Now I installed python3-pylatexenc via apt and everything works as expected.

Thanks for developing such a useful extension!
